### ISSUE TITLE
Issue in adding ProgBar

### ISSUE THREAD

**Issue by rishabh115** [knight-rider1609/MultiProgressBar#2]
I am trying to add ProgBar in FrameLayout but it is throwing Inflating Exception.
```
 Caused by: android.view.InflateException: Binary XML file line #26: Binary XML file line #26: Error inflating class com.aseem.versatileprogressbar.ProgBar
     Caused by: android.view.InflateException: Binary XML file line #26: Error inflating class com.aseem.versatileprogressbar.ProgBar
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
```
I implemented it in the exact same way as mentioned in the documentation but its not working.

**Comment by raymondgitonga** [comment]
Same here

**Comment by manmohan777** [comment]
I am facing the same issue. Did someone found the solution ?

**Comment by vikram-kadam** [comment]
Same issue
